In [119]:
from sklearn import tree
import pandas as pd
import os

# read in csv file and make dataframe

In [120]:
df = pd.read_csv('/Users/marlonschieber/Desktop/weather_api/model_input.csv')
df.head()

,date,aqi,precip,humidity,windspeed,winddir,acres_burned,temp_f,cloud_cover
0,1/1/17,18,0.0,75,10,269,0.0,51,51
1,1/2/17,5,0.0,78,7,198,0.0,49,49
2,1/3/17,0,2.4,89,13,149,0.0,54,54
3,1/4/17,10,1.1,90,7,271,0.0,55,55
4,1/5/17,10,0.0,65,5,200,0.0,48,48

# set aqi as target, remove unwanted columns, and set data variable

In [121]:
target = df["aqi"]

In [122]:
data = df.drop("date", axis=1)
data = data.drop("aqi", axis=1)
feature_names = data.columns
data.head()

   precip  humidity  windspeed  winddir  acres_burned  temp_f  cloud_cover
0     0.0        75         10      269           0.0      51           51
1     0.0        78          7      198           0.0      49           49
2     2.4        89         13      149           0.0      54           54
3     1.1        90          7      271           0.0      55           55
4     0.0        65          5      200           0.0      48           48

# split data and set x and y variables

In [123]:
 from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

# find score of decision tree, and random forest

In [124]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.03825136612021858

In [125]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.03278688524590164

# list order of importance of variables for tree and forest classifiers

In [126]:
 sorted(zip(clf.feature_importances_, feature_names), reverse=True)

[(0.23739808662108158, 'winddir'),
 (0.20839354025969728, 'humidity'),
 (0.13521720679028848, 'windspeed'),
 (0.1297198437151778, 'cloud_cover'),
 (0.12472005918976264, 'temp_f'),
 (0.10842942354531834, 'acres_burned'),
 (0.05612183987867385, 'precip')]

In [127]:
 sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.21652901436594674, 'winddir'),
 (0.20161107914147688, 'humidity'),
 (0.1470681934247492, 'temp_f'),
 (0.1460900136349943, 'cloud_cover'),
 (0.1296620801456762, 'windspeed'),
 (0.09315167765510049, 'acres_burned'),
 (0.06588794163205605, 'precip')]

# re-attempt model with a single variable to achieve a higher score

In [128]:
data = pd.DataFrame({
    'winddir': df['winddir']
})

feature_names = data.columns 
data.head()

   winddir
0      269
1      198
2      149
3      271
4      200

In [129]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [130]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.02185792349726776

# apply filter on dates, to run models on fire seasons only for both years

In [131]:
#  convert to datetime
df['date'] = pd.to_datetime(df['date'])

start_date = '06/30/2017'
end_date = '12/31/2017'

mask1 = (df['date'] > start_date) & (df['date'] <= end_date)


df1 = df.loc[mask1]
df1


df['date'] = pd.to_datetime(df['date'])

start_date = '06/30/2018'
end_date = '12/31/2018'

mask2 = (df['date'] > start_date) & (df['date'] <= end_date)


df2 = df.loc[mask2]
df2

,date,aqi,precip,humidity,windspeed,winddir,acres_burned,temp_f,cloud_cover
546,2018-07-01,17,0.0,70,6,244,6449.142857,77,77
547,2018-07-02,24,0.0,76,6,244,6449.142857,74,74
548,2018-07-03,54,0.1,73,7,224,6449.142857,73,73
549,2018-07-04,49,0.1,75,7,233,6449.142857,67,67
550,2018-07-05,32,0.0,67,5,258,9904.415584,75,75
551,2018-07-06,40,0.0,55,4,263,9904.415584,81,81
552,2018-07-07,42,0.0,54,6,262,9904.415584,82,82
553,2018-07-08,46,0.0,59,6,247,9904.415584,79,79
554,2018-07-09,44,0.0,53,6,257,9904.415584,83,83
555,2018-07-10,47,0.0,58,6,251,9904.415584,82,82
556,2018-07-11,32,0.1,70,5,236,9904.415584,79,79
557,2018-07-12,24,1.4,70,5,254,9904.415584,76,76
558,2018-07-13,24,2.4,72,5,257,12596.110030,77,77
559,2018-07-14,15,0.0,72,6,253,12596.110030,76,76
560,2018-07-15,30,0.0,73,6,245,6503.359695,74,74
561,2018-07-16,31,0.0,70,5,249,6503.359695,78,78
562,2018-07-17,28,0.1,73,5,246,3048.086968,78,78
563,2018-07-18,31,0.1,73,5,242,3048.086968,79,79
564,2018-07-19,34,0.0,69,5,246,3048.086968,80,80
565,2018-07-20,42,0.0,67,5,251,3048.086968,79,79
566,2018-07-21,31,0.0,68,6,249,3048.086968,79,79
567,2018-07-22,33,0.0,73,6,251,3048.086968,78,78
568,2018-07-23,32,0.0,67,6,253,9091.534336,79,79
569,2018-07-24,35,0.0,70,6,249,9091.534336,78,78
570,2018-07-25,14,0.0,64,5,251,9091.534336,84,84
571,2018-07-26,15,0.1,75,6,243,9091.534336,78,78
572,2018-07-27,6,0.0,77,6,246,17754.232450,74,74
573,2018-07-28,0,0.1,72,5,242,17754.232450,79,79
574,2018-07-29,0,0.1,76,5,242,17754.232450,76,76
575,2018-07-30,4,0.0,72,5,243,17754.232450,78,78
...,...,...,...,...,...,...,...,...,...
700,2018-12-02,21,0.0,76,6,128,0.000000,50,50
701,2018-12-03,30,0.0,75,7,58,0.000000,52,52
702,2018-12-04,40,3.7,80,10,64,0.000000,50,50
703,2018-12-05,32,1.4,87,11,51,0.000000,50,50
704,2018-12-06,47,0.0,79,7,49,0.000000,55,55
705,2018-12-07,54,0.0,76,3,43,0.000000,53,53
706,2018-12-08,70,0.0,81,5,52,0.000000,53,53
707,2018-12-09,76,0.0,85,3,53,0.000000,53,53
708,2018-12-10,74,0.4,88,4,127,0.000000,50,50
709,2018-12-11,54,0.0,81,4,200,0.000000,53,53
710,2018-12-12,55,0.0,78,6,170,0.000000,56,56
711,2018-12-13,58,0.0,66,6,64,0.000000,53,53
712,2018-12-14,63,3.6,77,7,133,0.000000,53,53
713,2018-12-15,50,4.0,88,5,144,0.000000,57,57
714,2018-12-16,26,14.5,86,10,164,0.000000,56,56
715,2018-12-17,38,1.2,85,5,244,0.000000,53,53
716,2018-12-18,45,0.0,91,3,206,0.000000,55,55
717,2018-12-19,45,0.0,91,4,56,0.000000,57,57
718,2018-12-20,64,0.0,90,3,117,0.000000,54,54
719,2018-12-21,46,1.2,88,5,198,0.000000,53,53
720,2018-12-22,35,0.0,80,4,86,0.000000,53,53
721,2018-12-23,51,0.3,85,3,232,0.000000,53,53
722,2018-12-24,48,1.3,95,9,194,0.000000,53,53
723,2018-12-25,28,0.8,75,9,312,0.000000,52,52
724,2018-12-26,27,0.0,74,5,297,0.000000,54,54
725,2018-12-27,19,0.0,71,9,283,0.000000,52,52
726,2018-12-28,23,0.0,52,9,21,0.000000,53,53
727,2018-12-29,39,0.0,59,3,121,0.000000,53,53
728,2018-12-30,56,0.0,79,4,176,0.000000,53,53
729,2018-12-31,12,0.0,56,9,117,0.000000,53,53

In [132]:
final_df = pd.concat([df1, df2], ignore_index=True)
final_df

,date,aqi,precip,humidity,windspeed,winddir,acres_burned,temp_f,cloud_cover
0,2017-07-01,41,0.1,77,9,240,396.915663,70,70
1,2017-07-02,20,0.1,78,6,225,396.915663,73,73
2,2017-07-03,18,0.0,76,6,248,396.915663,75,75
3,2017-07-04,22,0.0,77,6,248,396.915663,74,74
4,2017-07-05,9,0.0,76,6,252,396.915663,74,74
5,2017-07-06,25,0.0,64,6,252,396.915663,81,81
6,2017-07-07,45,0.0,52,6,251,396.915663,89,89
7,2017-07-08,54,0.0,47,6,243,396.915663,88,88
8,2017-07-09,50,0.0,68,6,241,396.915663,79,79
9,2017-07-10,45,0.0,74,7,237,396.915663,76,76
10,2017-07-11,55,0.0,72,7,236,8770.215663,74,74
11,2017-07-12,39,0.0,73,6,241,8770.215663,76,76
12,2017-07-13,25,0.0,75,6,238,8770.215663,75,75
13,2017-07-14,34,0.0,72,6,237,8770.215663,76,76
14,2017-07-15,48,0.0,61,5,238,8770.215663,83,83
15,2017-07-16,57,0.0,44,6,249,10868.318230,90,90
16,2017-07-17,55,0.0,55,7,247,10868.318230,81,81
17,2017-07-18,40,0.1,76,8,240,10868.318230,69,69
18,2017-07-19,39,0.0,71,6,238,10868.318230,77,77
19,2017-07-20,47,0.0,71,6,237,10868.318230,74,74
20,2017-07-21,37,0.0,67,6,235,10868.318230,78,78
21,2017-07-22,42,0.0,59,4,226,2495.018227,84,84
22,2017-07-23,17,0.0,60,5,242,2495.018227,84,84
23,2017-07-24,18,0.0,71,5,237,6108.931270,76,76
24,2017-07-25,15,0.0,72,5,252,6108.931270,76,76
25,2017-07-26,19,0.0,72,5,258,6108.931270,78,78
26,2017-07-27,22,0.0,63,5,239,6108.931270,82,82
27,2017-07-28,41,0.0,68,6,236,6108.931270,77,77
28,2017-07-29,35,0.0,73,5,241,6108.931270,75,75
29,2017-07-30,15,0.1,71,5,247,6108.931270,78,78
...,...,...,...,...,...,...,...,...,...
338,2018-12-02,21,0.0,76,6,128,0.000000,50,50
339,2018-12-03,30,0.0,75,7,58,0.000000,52,52
340,2018-12-04,40,3.7,80,10,64,0.000000,50,50
341,2018-12-05,32,1.4,87,11,51,0.000000,50,50
342,2018-12-06,47,0.0,79,7,49,0.000000,55,55
343,2018-12-07,54,0.0,76,3,43,0.000000,53,53
344,2018-12-08,70,0.0,81,5,52,0.000000,53,53
345,2018-12-09,76,0.0,85,3,53,0.000000,53,53
346,2018-12-10,74,0.4,88,4,127,0.000000,50,50
347,2018-12-11,54,0.0,81,4,200,0.000000,53,53
348,2018-12-12,55,0.0,78,6,170,0.000000,56,56
349,2018-12-13,58,0.0,66,6,64,0.000000,53,53
350,2018-12-14,63,3.6,77,7,133,0.000000,53,53
351,2018-12-15,50,4.0,88,5,144,0.000000,57,57
352,2018-12-16,26,14.5,86,10,164,0.000000,56,56
353,2018-12-17,38,1.2,85,5,244,0.000000,53,53
354,2018-12-18,45,0.0,91,3,206,0.000000,55,55
355,2018-12-19,45,0.0,91,4,56,0.000000,57,57
356,2018-12-20,64,0.0,90,3,117,0.000000,54,54
357,2018-12-21,46,1.2,88,5,198,0.000000,53,53
358,2018-12-22,35,0.0,80,4,86,0.000000,53,53
359,2018-12-23,51,0.3,85,3,232,0.000000,53,53
360,2018-12-24,48,1.3,95,9,194,0.000000,53,53
361,2018-12-25,28,0.8,75,9,312,0.000000,52,52
362,2018-12-26,27,0.0,74,5,297,0.000000,54,54
363,2018-12-27,19,0.0,71,9,283,0.000000,52,52
364,2018-12-28,23,0.0,52,9,21,0.000000,53,53
365,2018-12-29,39,0.0,59,3,121,0.000000,53,53
366,2018-12-30,56,0.0,79,4,176,0.000000,53,53
367,2018-12-31,12,0.0,56,9,117,0.000000,53,53

In [133]:
target = final_df["aqi"]

data = final_df.drop("date", axis=1)
data = data.drop("aqi", axis=1)
feature_names = data.columns
data.head()

   precip  humidity  windspeed  winddir  acres_burned  temp_f  cloud_cover
0     0.1        77          9      240    396.915663      70           70
1     0.1        78          6      225    396.915663      73           73
2     0.0        76          6      248    396.915663      75           75
3     0.0        77          6      248    396.915663      74           74
4     0.0        76          6      252    396.915663      74           74

# re-attempt models on fire seasons of both years to achieve higher score

In [134]:
 from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [135]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.05434782608695652

In [139]:
sorted(zip(clf.feature_importances_, feature_names), reverse=True)

[(0.24814703554835882, 'winddir'),
 (0.16726012813787416, 'cloud_cover'),
 (0.14576822580118948, 'humidity'),
 (0.1380113067207116, 'acres_burned'),
 (0.13104030963122604, 'temp_f'),
 (0.11579890933489169, 'windspeed'),
 (0.0539740848257483, 'precip')]

In [136]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.06521739130434782

In [137]:
 sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.21652890249992165, 'winddir'),
 (0.19176324385485097, 'humidity'),
 (0.14200388819264892, 'cloud_cover'),
 (0.14037224013265023, 'temp_f'),
 (0.12858214438504578, 'acres_burned'),
 (0.1183288660325556, 'windspeed'),
 (0.062420714902326785, 'precip')]